[package]
name = "parsec_api_crypto"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.5"
serde = {version = "1.0.127", features = ["derive"]}
serde_bytes = {version = "0.11.5"}
hex = "0.4"

sodiumoxide = {version="0.2.7", optional=true}

rand = {version="0.7", optional=true}
digest = {version="0.9.0", optional=true}
generic-array = {version="0.14.4", optional=true, features=["serde"]}
sha2 = {version="0.9.8", optional=true}
xsalsa20poly1305 = {version="0.8.0", optional=true}
ed25519-dalek = {version="1.0.1", optional=true}
x25519-dalek = {version="1.2.0", optional=true}
crypto_box = {version="0.7.0", optional=true, features=["std"]}
blake2 = {version="0.9.2", optional=true}

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = {version="0.2.3", features=["js"]}

[dev-dependencies]
pretty_assertions = "1.0.0"
serde_test = "1.0.130"
hex-literal = "0.3.3"
rmp-serde = "0.15.5"

[features]
default = ["use-sodiumoxide"]
# default = ["use-rustcrypto"]
use-sodiumoxide = ["sodiumoxide"]
use-rustcrypto = [
    "rand",
    "digest",
    "generic-array",
    "sha2",
    "xsalsa20poly1305",
    "ed25519-dalek",
    "x25519-dalek",
    "crypto_box",
    "blake2",
]
