[package]
name = "libparsec_client_connection"
version = "0.1.0"
edition = "2021"
autotests = false

[[test]]
name = "auth_cmds"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libparsec_crypto = { path = "../crypto", features = ["use-sodiumoxide"] }
[target.'cfg(target_arch = "wasm32")'.dependencies]
libparsec_crypto = { path = "../crypto", features = ["use-rustcrypto"] }

[dependencies]
# Used to send HTTP request to the server.
reqwest = "0.11.12"
# Used to perform operation on URL.
url = "2.3.1"
# Add primitive type to be used with the protocol
libparsec_types = { path = "../types" }
# Provide possible command to send to the server
libparsec_protocol = { path = "../protocol" }
# Use abstract crypto primitive, to allow to sign request.
# Used to encoded binary data.
base64 = "0.13.1"
chrono = "0.4.22"

[dev-dependencies]
anyhow = "1.0.66"
env_logger = "0.10.0"
http-body = "0.4.5"
hyper = { version = "0.14.22", features = ["server"] }
log = "0.4.17"
tokio = { version = "1.21", features = ["rt", "macros", "sync"] }
