[package]
name = "libparsec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsec_api_crypto = { version = "0.0.0", path = "../crates/parsec_api_crypto" }
parsec_api_types = { version = "0.0.0", path = "../crates/parsec_api_types" }