[package]
name = "libparsec"
version = "0.1.0"
edition = "2021"
rust-version = "1.62.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto = { path = "crates/crypto" }
protocol = { path = "crates/protocol" }
types = { path = "crates/types" }
client_types = { path = "crates/client_types" }
core = { path = "crates/core" }
core_fs = { path = "crates/core_fs" }
platform_async = { path = "crates/platform_async" }

[features]
mock-time = ["types/mock-time"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
platform_native = { path = "crates/platform_native" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
platform_web = { path = "crates/platform_web" }
