[package]
name = "libparsec"
version = "0.1.0"
edition = "2021"
rust-version = "1.62.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libparsec_platform_native = { path = "../crates/platform_native", optional = true }
libparsec_platform_web = { path = "../crates/platform_web", optional = true }
api_crypto = { path = "crates/api_crypto" }
api_protocol = { path = "crates/api_protocol" }
api_types = { path = "crates/api_types" }

[features]
mock-time = ["api_types/mock-time"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libparsec_platform_native = { path = "../crates/platform_native" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
libparsec_platform_web = { path = "../crates/platform_web" }
