[package]
name = "libparsec_core"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libparsec_crypto = { path = "../crypto", features = ["use-sodiumoxide"] }
[target.'cfg(target_arch = "wasm32")'.dependencies]
libparsec_crypto = { path = "../crypto", features = ["use-rustcrypto"] }

[dependencies]
libparsec_protocol = { path = "../protocol" }
libparsec_types = { path = "../types" }

rmp-serde = "1.1.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "2.1.0"
thiserror = "1.0.37"

[dev-dependencies]
tests_fixtures = { path = "../tests_fixtures" }

rstest = "0.16.0"
chrono = "0.4.22"
