[package]
name = "core"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api_crypto = { path = "../api_crypto" }
api_protocol = { path = "../api_protocol" }
api_types = { path = "../api_types" }

thiserror = "1.0.30"

[dev-dependencies]
tests_fixtures = { path = "../../../crates/tests_fixtures" }

rstest = "0.13.0"
chrono = "0.4.19"
